"use client";

import {
  createContext,
  useContext,
  useState,
  type ReactNode,
} from "react";

export type Language = "en" | "fr" | "ko";

const STORAGE_KEY = "coffee-beans-language";

const languageOptions: Array<{ code: Language; label: string }> = [
  { code: "en", label: "English" },
  { code: "fr", label: "Francais" },
  { code: "ko", label: "한국어" },
];

const translations = {
  en: {
    locale: "en-US",
    languageLabel: "Language",
    navHome: "Home",
    navMyBeans: "Saved Beans",
    navCoffeeGuide: "Coffee Guide",
    navAddBean: "Add Bean",
    personalCoffeeLog: "Personal Coffee Log",
    heroTitle: "Every coffee tells a story, keep yours organized.",
    heroDescription:
      "Track your beans from purchase to taste, and know exactly which ones are worth buying again.",
    heroImageAlt: "Coffee beans preview",
    addBeanTitle: "Add a New Bean",
    addBeanDescription:
      "Save a coffee bean with its taste notes and buying details.",
    imageHelp: "Optional image: JPG, PNG, or WEBP up to 4.5 MB.",
    saveBean: "Save bean",
    savingBean: "Saving bean...",
    beanSaved: "Coffee bean saved to your catalog.",
    networkSaveError: "Network error while saving the bean. Please try again.",
    genericSaveError: "Unable to save this bean.",
    catalog: "Catalog",
    savedBeans: "Saved beans",
    catalogDescription:
      "Compare your saved beans by drink style, price, and the notes you want to remember next time.",
    entriesShown: "entries shown",
    entryShown: "entry shown",
    filterByBrand: "Filter by brand",
    filterByRoast: "Filter by roast",
    sortBy: "Sort by",
    newestFirst: "Newest first",
    oldestFirst: "Oldest first",
    priceHighToLow: "Price high to low",
    priceLowToHigh: "Price low to high",
    allBrands: "All brands",
    allRoasts: "All roasts",
    noMatches: "No matches",
    noMatchesDescription: "Try a different brand or roast filter to see more beans.",
    noBeansYet: "No beans yet",
    firstRoast: "Your first roast can go here.",
    emptyDescription:
      "Add your coffee details to start building a polished catalog. Images are optional.",
    brand: "Brand",
    brandPlaceholder: "Choose or type a brand",
    price: "Price (EUR)",
    quantity: "Qty",
    weight: "Weight (g)",
    rating: "Rating",
    roastLabel: "Roast",
    roastHelper:
      "Choose the roast type for this bean, from light and bright to dark and bold.",
    comments: "Comments",
    commentsPlaceholder: "Chocolate notes, citrus finish, excellent with espresso...",
    imageLabel: "Bean Image (optional)",
    editBean: "Edit bean",
    cancel: "Cancel",
    saveChanges: "Save changes",
    savingChanges: "Saving changes...",
    close: "Close",
    updateError: "Unable to update this bean.",
    updateNetworkError: "Network error while updating the bean. Please try again.",
    updatedMessage: "Coffee bean updated successfully.",
    deleteConfirm: "Are you sure you want to delete this coffee bean?",
    deleteError: "Unable to delete this bean.",
    deleteNetworkError: "Network error while deleting the bean. Please try again.",
    deletedMessage: "Coffee bean deleted successfully.",
    beanRemoved: "Bean removed",
    addedOn: "Added",
    priceLabel: "Price",
    weightLabel: "Weight",
    unitPriceLabel: "Unit price",
    priceTrend: "Price trend",
    priceTrendLow: "Low",
    priceTrendHigh: "High",
    priceTrendAboveAverage: "Above average",
    priceTrendBelowAverage: "Below average",
    priceTrendAverage: "Near average",
    quantityLabel: "Qty",
    recommendedLabel: "Recommended",
    noComments: "No tasting notes or comments added yet.",
    edit: "Edit",
    delete: "Delete",
    working: "Working...",
    coffeePrices: {
      title: "Coffee Prices",
      subtitle: "Track price changes over time and compare coffee brands by drink, size, and milk choice.",
      tabAddCoffee: "Add Coffee",
      tabPriceTrend: "Price per Brand",
      tabOrderHistory: "Order History",
      backToCoffeeBean: "Back to Coffee Bean",
      addCoffeeTitle: "Add Coffee",
      addSuccess: "Order added to your price tracker.",
      addValidationError: "Add a brand, a valid final price, and a date to save the order.",
      brand: "Brand",
      otherBrand: "Other brand",
      otherBrandPlaceholder: "Enter a coffee brand",
      drinkType: "Drink type",
      temperature: "Temperature",
      milkType: "Milk type",
      size: "Size",
      date: "Date",
      priceEur: "Price (EUR)",
      notes: "Notes",
      notesPlaceholder: "Optional notes like cafe location, promo, or cup size details.",
      add: "Add",
      trendTitle: "Price Trend Over Time",
      reset: "Reset",
      search: "Search",
      from: "From",
      to: "To",
      selectedCoffee: "Selected coffee",
      matches: "Matches",
      period: "Period",
      firstPrice: "First price",
      latestPrice: "Latest price",
      change: "Change",
      notEnoughData: "Not enough data yet",
      notEnoughDataDescription: "Choose one brand and a matching setup with at least two entries to see the trend clearly.",
      brandComparisonTitle: "Price per Product",
      brandComparisonDescription: "Compare prices across different brands for the same coffee configuration.",
      notEnoughBrands: "Not enough brands",
      notEnoughBrandsDescription: "Need at least two brands with matching orders to compare prices.",
      orderHistoryTitle: "Order History",
      noOrders: "No recent orders match these filters",
      noOrdersDescription: "Try a different setup or date range to bring entries back into view.",
      deleteOrder: "Delete",
      deleteOrderConfirm: "Are you sure you want to delete this order?",
      tableDate: "Date",
      tableBrand: "Brand",
      tableDrink: "Drink",
      tableTemperature: "Hot/Iced",
      tableMilk: "Milk",
      tableSize: "Size",
      tablePrice: "Price (EUR)",
      allBrands: "All brands",
      latte: "Latte",
      americano: "Americano",
      hot: "Hot",
      iced: "Iced",
      normal: "Normal",
      oat: "Oat",
      none: "None",
      small: "Small",
      standard: "Standard",
      large: "Large",
    },
    bestForOptions: {
      Light: "Light",
      "Medium-Light": "Medium-Light",
      Medium: "Medium",
      "Medium-Dark": "Medium-Dark",
      Dark: "Dark",
    },
  },
  fr: {
    locale: "fr-FR",
    languageLabel: "Langue",
    navHome: "Accueil",
    navMyBeans: "Cafes sauvegardes",
    navCoffeeGuide: "Guide cafe",
    navAddBean: "Ajouter",
    personalCoffeeLog: "Journal de cafe personnel",
    heroTitle: "Chaque cafe raconte une histoire, gardez la votre bien organisee.",
    heroDescription:
      "Suivez vos grains de l'achat a la degustation et sachez exactement lesquels meritent d'etre rachetes.",
    heroImageAlt: "Apercu des grains de cafe",
    addBeanTitle: "Ajouter un nouveau cafe",
    addBeanDescription:
      "Enregistrez un cafe avec ses notes de gout et ses details d'achat.",
    imageHelp: "Image facultative : JPG, PNG ou WEBP jusqu'a 4,5 Mo.",
    saveBean: "Enregistrer",
    savingBean: "Enregistrement...",
    beanSaved: "Le cafe a ete ajoute a votre catalogue.",
    networkSaveError: "Erreur reseau pendant l'enregistrement. Veuillez reessayer.",
    genericSaveError: "Impossible d'enregistrer ce cafe.",
    catalog: "Catalogue",
    savedBeans: "Cafes enregistres",
    catalogDescription:
      "Comparez vos cafes enregistres selon la boisson, le prix et les notes que vous voulez garder en memoire.",
    entriesShown: "elements affiches",
    entryShown: "element affiche",
    filterByBrand: "Filtrer par marque",
    filterByRoast: "Filtrer par torrefaction",
    sortBy: "Trier par",
    newestFirst: "Plus recent d'abord",
    oldestFirst: "Plus ancien d'abord",
    priceHighToLow: "Prix du plus eleve au plus bas",
    priceLowToHigh: "Prix du plus bas au plus eleve",
    allBrands: "Toutes les marques",
    allRoasts: "Toutes les torrefactions",
    noMatches: "Aucun resultat",
    noMatchesDescription:
      "Essayez une autre marque ou une autre torrefaction pour voir plus de cafes.",
    noBeansYet: "Aucun cafe pour l'instant",
    firstRoast: "Votre premier cafe peut commencer ici.",
    emptyDescription:
      "Ajoutez les details de votre cafe pour commencer un catalogue elegant. Les images sont facultatives.",
    brand: "Marque",
    brandPlaceholder: "Choisissez ou saisissez une marque",
    price: "Prix (EUR)",
    quantity: "Qt",
    weight: "Poids (g)",
    rating: "Note",
    roastLabel: "Torrefaction",
    roastHelper:
      "Choisissez la torrefaction de ce cafe, d'une tasse claire et vive a une tasse plus sombre et intense.",
    comments: "Commentaires",
    commentsPlaceholder: "Notes chocolat, finale agrumee, excellent pour l'espresso...",
    imageLabel: "Image du cafe (facultative)",
    editBean: "Modifier le cafe",
    cancel: "Annuler",
    saveChanges: "Enregistrer les modifications",
    savingChanges: "Enregistrement des modifications...",
    close: "Fermer",
    updateError: "Impossible de mettre a jour ce cafe.",
    updateNetworkError: "Erreur reseau pendant la mise a jour. Veuillez reessayer.",
    updatedMessage: "Le cafe a ete mis a jour avec succes.",
    deleteConfirm: "Voulez-vous vraiment supprimer ce cafe ?",
    deleteError: "Impossible de supprimer ce cafe.",
    deleteNetworkError: "Erreur reseau pendant la suppression. Veuillez reessayer.",
    deletedMessage: "Le cafe a ete supprime avec succes.",
    beanRemoved: "Cafe supprime",
    addedOn: "Ajoute le",
    priceLabel: "Prix",
    weightLabel: "Poids",
    unitPriceLabel: "Prix unitaire",
    priceTrend: "Tendance du prix",
    priceTrendLow: "Bas",
    priceTrendHigh: "Haut",
    priceTrendAboveAverage: "Au-dessus de la moyenne",
    priceTrendBelowAverage: "En dessous de la moyenne",
    priceTrendAverage: "Proche de la moyenne",
    quantityLabel: "Qt",
    recommendedLabel: "Recommande",
    noComments: "Aucune note de degustation ni commentaire pour le moment.",
    edit: "Modifier",
    delete: "Supprimer",
    working: "En cours...",
    coffeePrices: {
      title: "Prix du cafe",
      subtitle: "Suivez l'evolution des prix et comparez les marques selon la boisson, la taille et le type de lait.",
      tabAddCoffee: "Ajouter un cafe",
      tabPriceTrend: "Prix par marque",
      tabOrderHistory: "Historique des commandes",
      backToCoffeeBean: "Retour au cafe",
      addCoffeeTitle: "Ajouter un cafe",
      addSuccess: "La commande a ete ajoutee a votre suivi des prix.",
      addValidationError: "Ajoutez une marque, un prix valide et une date pour enregistrer la commande.",
      brand: "Marque",
      otherBrand: "Autre marque",
      otherBrandPlaceholder: "Saisissez une marque de cafe",
      drinkType: "Type de boisson",
      temperature: "Temperature",
      milkType: "Type de lait",
      size: "Taille",
      date: "Date",
      priceEur: "Prix (EUR)",
      notes: "Notes",
      notesPlaceholder: "Notes facultatives comme le cafe, une promo ou des details de taille.",
      add: "Ajouter",
      trendTitle: "Tendance des prix",
      reset: "Reinitialiser",
      search: "Rechercher",
      from: "Du",
      to: "Au",
      selectedCoffee: "Cafe selectionne",
      matches: "Correspondances",
      period: "Periode",
      firstPrice: "Premier prix",
      latestPrice: "Dernier prix",
      change: "Variation",
      notEnoughData: "Pas encore assez de donnees",
      notEnoughDataDescription: "Choisissez une marque et une configuration avec au moins deux entrees pour voir clairement la tendance.",
      brandComparisonTitle: "Prix par produit",
      brandComparisonDescription: "Comparez les prix entre differentes marques pour la meme configuration de cafe.",
      notEnoughBrands: "Pas assez de marques",
      notEnoughBrandsDescription: "Besoin d'au moins deux marques avec des commandes correspondantes pour comparer les prix.",
      orderHistoryTitle: "Historique des commandes",
      noOrders: "Aucune commande recente ne correspond a ces filtres",
      noOrdersDescription: "Essayez une autre configuration ou une autre periode pour afficher des entrees.",
      deleteOrder: "Supprimer",
      deleteOrderConfirm: "Voulez-vous vraiment supprimer cette commande ?",
      tableDate: "Date",
      tableBrand: "Marque",
      tableDrink: "Boisson",
      tableTemperature: "Chaud/Glace",
      tableMilk: "Lait",
      tableSize: "Taille",
      tablePrice: "Prix (EUR)",
      allBrands: "Toutes les marques",
      latte: "Latte",
      americano: "Americano",
      hot: "Chaud",
      iced: "Glace",
      normal: "Classique",
      oat: "Avoine",
      none: "Aucun",
      small: "Petit",
      standard: "Standard",
      large: "Grand",
    },
    bestForOptions: {
      Light: "Clair",
      "Medium-Light": "Clair-moyen",
      Medium: "Moyen",
      "Medium-Dark": "Moyen-fonce",
      Dark: "Fonce",
    },
  },
  ko: {
    locale: "ko-KR",
    languageLabel: "언어",
    navHome: "홈",
    navMyBeans: "저장된 원두",
    navCoffeeGuide: "커피 가이드",
    navAddBean: "원두 추가",
    personalCoffeeLog: "개인 커피 로그",
    heroTitle: "모든 커피에는 이야기가 있습니다. 깔끔하게 정리해 보세요.",
    heroDescription:
      "구매부터 맛 기록까지 원두를 추적하고, 다시 사고 싶은 원두를 바로 확인하세요.",
    heroImageAlt: "커피 원두 미리보기",
    addBeanTitle: "새 원두 추가",
    addBeanDescription:
      "맛 노트와 구매 정보를 함께 저장하세요.",
    imageHelp: "선택 이미지: JPG, PNG, WEBP, 최대 4.5MB.",
    saveBean: "원두 저장",
    savingBean: "저장 중...",
    beanSaved: "원두가 카탈로그에 저장되었습니다.",
    networkSaveError: "저장 중 네트워크 오류가 발생했습니다. 다시 시도해 주세요.",
    genericSaveError: "이 원두를 저장할 수 없습니다.",
    catalog: "카탈로그",
    savedBeans: "저장된 원두",
    catalogDescription:
      "저장한 원두를 음료 스타일, 가격, 그리고 기억하고 싶은 메모 기준으로 비교해 보세요.",
    entriesShown: "개 표시 중",
    entryShown: "개 표시 중",
    filterByBrand: "브랜드로 필터",
    filterByRoast: "로스트로 필터",
    sortBy: "정렬 기준",
    newestFirst: "최신순",
    oldestFirst: "오래된순",
    priceHighToLow: "가격 높은순",
    priceLowToHigh: "가격 낮은순",
    allBrands: "모든 브랜드",
    allRoasts: "모든 로스트",
    noMatches: "일치하는 항목 없음",
    noMatchesDescription: "다른 브랜드나 로스트를 선택해 더 많은 원두를 확인해 보세요.",
    noBeansYet: "아직 원두가 없습니다",
    firstRoast: "첫 번째 로스트를 여기에 기록할 수 있습니다.",
    emptyDescription:
      "커피 정보를 추가해 깔끔한 카탈로그를 시작하세요. 이미지는 선택 사항입니다.",
    brand: "브랜드",
    brandPlaceholder: "브랜드를 선택하거나 입력하세요",
    price: "가격 (EUR)",
    quantity: "수량",
    weight: "중량 (g)",
    rating: "평점",
    roastLabel: "로스트",
    roastHelper:
      "이 원두의 로스트 타입을 선택하세요. 밝고 산뜻한 스타일부터 진하고 묵직한 스타일까지 고를 수 있어요.",
    comments: "코멘트",
    commentsPlaceholder: "초콜릿 노트, 시트러스 피니시, 에스프레소에 잘 어울림...",
    imageLabel: "원두 이미지 (선택)",
    editBean: "원두 수정",
    cancel: "취소",
    saveChanges: "변경 저장",
    savingChanges: "변경 저장 중...",
    close: "닫기",
    updateError: "이 원두를 수정할 수 없습니다.",
    updateNetworkError: "수정 중 네트워크 오류가 발생했습니다. 다시 시도해 주세요.",
    updatedMessage: "원두가 성공적으로 수정되었습니다.",
    deleteConfirm: "이 원두를 정말 삭제하시겠습니까?",
    deleteError: "이 원두를 삭제할 수 없습니다.",
    deleteNetworkError: "삭제 중 네트워크 오류가 발생했습니다. 다시 시도해 주세요.",
    deletedMessage: "원두가 성공적으로 삭제되었습니다.",
    beanRemoved: "원두 삭제됨",
    addedOn: "추가일",
    priceLabel: "가격",
    weightLabel: "중량",
    unitPriceLabel: "그램당 가격",
    priceTrend: "가격 추세",
    priceTrendLow: "낮음",
    priceTrendHigh: "높음",
    priceTrendAboveAverage: "평균 이상",
    priceTrendBelowAverage: "평균 이하",
    priceTrendAverage: "평균 수준",
    quantityLabel: "수량",
    recommendedLabel: "추천",
    noComments: "아직 시음 노트나 코멘트가 없습니다.",
    edit: "수정",
    delete: "삭제",
    working: "처리 중...",
    coffeePrices: {
      title: "커피 가격",
      subtitle: "음료, 사이즈, 우유 선택에 따라 가격 변화를 추적하고 브랜드를 비교해 보세요.",
      tabAddCoffee: "커피 추가",
      tabPriceTrend: "브랜드별 가격",
      tabOrderHistory: "주문 기록",
      backToCoffeeBean: "커피 원두로 돌아가기",
      addCoffeeTitle: "커피 추가",
      addSuccess: "주문이 가격 추적기에 추가되었습니다.",
      addValidationError: "브랜드, 올바른 가격, 날짜를 입력해 주문을 저장해 주세요.",
      brand: "브랜드",
      otherBrand: "기타 브랜드",
      otherBrandPlaceholder: "커피 브랜드를 입력하세요",
      drinkType: "음료 종류",
      temperature: "온도",
      milkType: "우유 종류",
      size: "사이즈",
      date: "날짜",
      priceEur: "가격 (EUR)",
      notes: "메모",
      notesPlaceholder: "카페 위치, 프로모션, 컵 크기 같은 선택 메모를 남겨 보세요.",
      add: "추가",
      trendTitle: "가격 추이",
      reset: "초기화",
      search: "검색",
      from: "시작",
      to: "끝",
      selectedCoffee: "선택한 커피",
      matches: "일치 수",
      period: "기간",
      firstPrice: "첫 가격",
      latestPrice: "최근 가격",
      change: "변화",
      notEnoughData: "아직 데이터가 부족합니다",
      notEnoughDataDescription: "가격 추이를 보려면 브랜드 하나와 조건에 맞는 항목 두 개 이상을 선택해 주세요.",
      brandComparisonTitle: "제품별 가격",
      brandComparisonDescription: "같은 커피 구성에 대해 다른 브랜드의 가격을 비교해 보세요.",
      notEnoughBrands: "브랜드가 부족합니다",
      notEnoughBrandsDescription: "가격을 비교하려면 일치하는 주문이 있는 브랜드 두 개 이상이 필요합니다.",
      orderHistoryTitle: "주문 기록",
      noOrders: "현재 필터와 일치하는 최근 주문이 없습니다",
      noOrdersDescription: "다른 설정이나 날짜 범위를 선택해 주문을 다시 표시해 보세요.",
      deleteOrder: "삭제",
      deleteOrderConfirm: "이 주문을 삭제하시겠습니까?",
      tableDate: "날짜",
      tableBrand: "브랜드",
      tableDrink: "음료",
      tableTemperature: "따뜻함/아이스",
      tableMilk: "우유",
      tableSize: "사이즈",
      tablePrice: "가격 (EUR)",
      allBrands: "모든 브랜드",
      latte: "라테",
      americano: "아메리카노",
      hot: "따뜻하게",
      iced: "아이스",
      normal: "일반",
      oat: "오트",
      none: "없음",
      small: "스몰",
      standard: "스탠다드",
      large: "라지",
    },
    bestForOptions: {
      Light: "라이트",
      "Medium-Light": "미디엄-라이트",
      Medium: "미디엄",
      "Medium-Dark": "미디엄-다크",
      Dark: "다크",
    },
  },
} satisfies Record<Language, Record<string, unknown>>;

type TranslationSet = (typeof translations)[Language];

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  messages: TranslationSet;
  languageOptions: typeof languageOptions;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === "undefined") {
      return "en";
    }

    const storedLanguage = window.localStorage.getItem(STORAGE_KEY) as Language | null;

    if (storedLanguage && storedLanguage in translations) {
      return storedLanguage;
    }

    return "en";
  });

  function handleSetLanguage(nextLanguage: Language) {
    setLanguage(nextLanguage);
    window.localStorage.setItem(STORAGE_KEY, nextLanguage);
  }

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: handleSetLanguage,
        messages: translations[language],
        languageOptions,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider.");
  }

  return context;
}
