export type CoffeeShopPriceEntry = {
  id: string;
  brand: string;
  drinkType: "Latte" | "Americano";
  temperature: "Hot" | "Iced";
  milkType: "Normal" | "Oat" | "None";
  size: "Small" | "Standard" | "Large";
  finalPrice: number;
  oatMilkExtra: number;
  date: string;
  notes?: string;
};

export const coffeeShopPriceData: CoffeeShopPriceEntry[] = [
  {
    id: "sb-latte-hot-standard-2025-01-12",
    brand: "Starbucks",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 4.9,
    oatMilkExtra: 0,
    date: "2025-01-12",
  },
  {
    id: "sb-latte-hot-standard-2025-03-02",
    brand: "Starbucks",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 5.1,
    oatMilkExtra: 0,
    date: "2025-03-02",
  },
  {
    id: "sb-latte-hot-standard-2025-05-20",
    brand: "Starbucks",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 5.3,
    oatMilkExtra: 0,
    date: "2025-05-20",
  },
  {
    id: "sb-latte-iced-large-oat-2025-02-14",
    brand: "Starbucks",
    drinkType: "Latte",
    temperature: "Iced",
    milkType: "Oat",
    size: "Large",
    finalPrice: 6.2,
    oatMilkExtra: 0.7,
    date: "2025-02-14",
  },
  {
    id: "sb-latte-iced-large-oat-2025-04-18",
    brand: "Starbucks",
    drinkType: "Latte",
    temperature: "Iced",
    milkType: "Oat",
    size: "Large",
    finalPrice: 6.5,
    oatMilkExtra: 0.7,
    date: "2025-04-18",
  },
  {
    id: "sb-americano-iced-standard-none-2025-04-28",
    brand: "Starbucks",
    drinkType: "Americano",
    temperature: "Iced",
    milkType: "None",
    size: "Standard",
    finalPrice: 4.4,
    oatMilkExtra: 0,
    date: "2025-04-28",
  },
  {
    id: "blue-latte-hot-standard-normal-2025-01-18",
    brand: "Blue Bottle",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 4.8,
    oatMilkExtra: 0,
    date: "2025-01-18",
  },
  {
    id: "blue-latte-hot-standard-normal-2025-03-18",
    brand: "Blue Bottle",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 5.0,
    oatMilkExtra: 0,
    date: "2025-03-18",
  },
  {
    id: "blue-latte-hot-standard-normal-2025-05-19",
    brand: "Blue Bottle",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 5.15,
    oatMilkExtra: 0,
    date: "2025-05-19",
  },
  {
    id: "blue-latte-iced-standard-oat-2025-02-05",
    brand: "Blue Bottle",
    drinkType: "Latte",
    temperature: "Iced",
    milkType: "Oat",
    size: "Standard",
    finalPrice: 5.9,
    oatMilkExtra: 0.6,
    date: "2025-02-05",
  },
  {
    id: "blue-latte-iced-standard-oat-2025-04-23",
    brand: "Blue Bottle",
    drinkType: "Latte",
    temperature: "Iced",
    milkType: "Oat",
    size: "Standard",
    finalPrice: 6.1,
    oatMilkExtra: 0.6,
    date: "2025-04-23",
  },
  {
    id: "blue-americano-hot-large-none-2025-05-25",
    brand: "Blue Bottle",
    drinkType: "Americano",
    temperature: "Hot",
    milkType: "None",
    size: "Large",
    finalPrice: 4.85,
    oatMilkExtra: 0,
    date: "2025-05-25",
  },
  {
    id: "arabica-latte-hot-standard-normal-2025-01-10",
    brand: "% Arabica",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 4.6,
    oatMilkExtra: 0,
    date: "2025-01-10",
  },
  {
    id: "arabica-latte-hot-standard-normal-2025-03-12",
    brand: "% Arabica",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 4.75,
    oatMilkExtra: 0,
    date: "2025-03-12",
  },
  {
    id: "arabica-latte-hot-standard-normal-2025-05-21",
    brand: "% Arabica",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 4.95,
    oatMilkExtra: 0,
    date: "2025-05-21",
  },
  {
    id: "arabica-latte-iced-large-oat-2025-02-20",
    brand: "% Arabica",
    drinkType: "Latte",
    temperature: "Iced",
    milkType: "Oat",
    size: "Large",
    finalPrice: 5.85,
    oatMilkExtra: 0.55,
    date: "2025-02-20",
  },
  {
    id: "arabica-latte-iced-large-oat-2025-04-24",
    brand: "% Arabica",
    drinkType: "Latte",
    temperature: "Iced",
    milkType: "Oat",
    size: "Large",
    finalPrice: 6.0,
    oatMilkExtra: 0.55,
    date: "2025-04-24",
  },
  {
    id: "arabica-americano-iced-standard-none-2025-05-15",
    brand: "% Arabica",
    drinkType: "Americano",
    temperature: "Iced",
    milkType: "None",
    size: "Standard",
    finalPrice: 4.1,
    oatMilkExtra: 0,
    date: "2025-05-15",
  },
  {
    id: "thecoffee-latte-hot-standard-normal-2025-01-22",
    brand: "The Coffee",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 4.4,
    oatMilkExtra: 0,
    date: "2025-01-22",
  },
  {
    id: "thecoffee-latte-hot-standard-normal-2025-03-26",
    brand: "The Coffee",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 4.55,
    oatMilkExtra: 0,
    date: "2025-03-26",
  },
  {
    id: "thecoffee-latte-hot-standard-normal-2025-05-17",
    brand: "The Coffee",
    drinkType: "Latte",
    temperature: "Hot",
    milkType: "Normal",
    size: "Standard",
    finalPrice: 4.7,
    oatMilkExtra: 0,
    date: "2025-05-17",
  },
  {
    id: "thecoffee-latte-iced-standard-oat-2025-02-09",
    brand: "The Coffee",
    drinkType: "Latte",
    temperature: "Iced",
    milkType: "Oat",
    size: "Standard",
    finalPrice: 5.4,
    oatMilkExtra: 0.5,
    date: "2025-02-09",
  },
  {
    id: "thecoffee-latte-iced-standard-oat-2025-04-16",
    brand: "The Coffee",
    drinkType: "Latte",
    temperature: "Iced",
    milkType: "Oat",
    size: "Standard",
    finalPrice: 5.55,
    oatMilkExtra: 0.5,
    date: "2025-04-16",
  },
  {
    id: "thecoffee-americano-hot-small-none-2025-05-11",
    brand: "The Coffee",
    drinkType: "Americano",
    temperature: "Hot",
    milkType: "None",
    size: "Small",
    finalPrice: 3.8,
    oatMilkExtra: 0,
    date: "2025-05-11",
  },
];

export const coffeeShopBrands = Array.from(
  new Set(coffeeShopPriceData.map((entry) => entry.brand)),
).sort((left, right) => left.localeCompare(right));
